/**
 * GET /api/ncrs
 *
 * Fetch NCRs (Non-Conformance Reports) with optional filters
 *
 * Query Parameters:
 * - locationId: Filter by location
 * - type: Filter by NCR type (MANUAL/PRICE_VARIANCE)
 * - status: Filter by NCR status
 * - startDate: Filter by created date (from)
 * - endDate: Filter by created date (to)
 * - autoGenerated: Filter by auto-generated flag (true/false)
 *
 * Permissions:
 * - User must have access to at least one location
 * - Supervisors and Admins can see all NCRs
 * - Operators can only see NCRs for their locations
 */

import prisma from "../../utils/prisma";
import { setCacheHeaders } from "../../utils/performance";
import { z } from "zod";
import type { UserRole } from "@prisma/client";

// User session type
interface AuthUser {
  id: string;
  username: string;
  email: string;
  role: UserRole;
  default_location_id: string | null;
}

// Query schema for validation
const querySchema = z.object({
  locationId: z.string().uuid().optional(),
  type: z.enum(["MANUAL", "PRICE_VARIANCE"]).optional(),
  status: z.enum(["OPEN", "CREDITED", "REJECTED", "RESOLVED"]).optional(),
  startDate: z.string().optional(), // ISO date string
  endDate: z.string().optional(), // ISO date string
  autoGenerated: z.enum(["true", "false"]).optional(),
  page: z.coerce.number().default(1),
  limit: z.coerce.number().max(200).default(50),
});

export default defineEventHandler(async (event) => {
  const user = event.context.user as AuthUser | undefined;

  if (!user) {
    throw createError({
      statusCode: 401,
      statusMessage: "Unauthorized",
      data: {
        code: "NOT_AUTHENTICATED",
        message: "You must be logged in to access this resource",
      },
    });
  }

  try {
    // Parse and validate query parameters
    const query = await getQuery(event);
    const { locationId, type, status, startDate, endDate, autoGenerated, page, limit } =
      querySchema.parse(query);

    // Build where clause for NCRs
    const where: Record<string, unknown> = {};

    // Admin and Supervisor can see all NCRs
    // Operators can only see NCRs for their locations
    if (user.role !== "ADMIN" && user.role !== "SUPERVISOR") {
      // Get user's accessible locations
      const userLocations = await prisma.userLocation.findMany({
        where: { user_id: user.id },
        select: { location_id: true },
      });

      const locationIds = userLocations.map((ul) => ul.location_id);

      if (locationIds.length === 0) {
        // User has no location access, return empty result
        return {
          ncrs: [],
          count: 0,
        };
      }

      // Filter NCRs where user has access to the location
      where.location_id = { in: locationIds };
    }

    if (locationId) {
      where.location_id = locationId;
    }

    if (type) {
      where.type = type;
    }

    if (status) {
      where.status = status;
    }

    if (autoGenerated === "true") {
      where.auto_generated = true;
    } else if (autoGenerated === "false") {
      where.auto_generated = false;
    }

    if (startDate || endDate) {
      const createdAtFilter: Record<string, Date> = {};
      if (startDate) {
        createdAtFilter.gte = new Date(startDate);
      }
      if (endDate) {
        createdAtFilter.lte = new Date(endDate);
      }
      where.created_at = createdAtFilter;
    }

    // Calculate pagination
    const skip = (page - 1) * limit;
    const take = limit;

    // Fetch NCRs with pagination
    const [ncrs, total] = await Promise.all([
      prisma.nCR.findMany({
        where,
        include: {
          location: {
            select: {
              id: true,
              code: true,
              name: true,
              type: true,
            },
          },
          delivery: {
            select: {
              id: true,
              delivery_no: true,
              delivery_date: true,
            },
          },
          delivery_line: {
            select: {
              id: true,
              item: {
                select: {
                  id: true,
                  code: true,
                  name: true,
                  unit: true,
                },
              },
              quantity: true,
              unit_price: true,
              period_price: true,
            },
          },
          creator: {
            select: {
              id: true,
              username: true,
              full_name: true,
              role: true,
            },
          },
        },
        orderBy: {
          created_at: "desc",
        },
        skip,
        take,
      }),
      prisma.nCR.count({ where }),
    ]);

    // Calculate pagination metadata
    const totalPages = Math.ceil(total / limit);
    const hasNextPage = page < totalPages;
    const hasPrevPage = page > 1;

    // Set cache headers (2 seconds for list data)
    setCacheHeaders(event, {
      maxAge: 2,
      staleWhileRevalidate: 2,
    });

    return {
      ncrs: ncrs.map((ncr) => ({
        id: ncr.id,
        ncr_no: ncr.ncr_no,
        location: ncr.location,
        type: ncr.type,
        auto_generated: ncr.auto_generated,
        delivery: ncr.delivery,
        delivery_line: ncr.delivery_line
          ? {
              id: ncr.delivery_line.id,
              item: ncr.delivery_line.item,
              quantity: ncr.delivery_line.quantity,
              unit_price: ncr.delivery_line.unit_price,
              period_price: ncr.delivery_line.period_price,
            }
          : null,
        reason: ncr.reason,
        quantity: ncr.quantity,
        value: ncr.value,
        status: ncr.status,
        creator: ncr.creator,
        created_at: ncr.created_at,
        resolved_at: ncr.resolved_at,
        resolution_notes: ncr.resolution_notes,
      })),
      pagination: {
        total,
        page,
        limit,
        totalPages,
        hasNextPage,
        hasPrevPage,
      },
    };
  } catch (error) {
    // Handle Zod validation errors
    if (error instanceof z.ZodError) {
      throw createError({
        statusCode: 400,
        statusMessage: "Bad Request",
        data: {
          code: "VALIDATION_ERROR",
          message: "Invalid query parameters",
          details: error.issues,
        },
      });
    }

    // Re-throw createError errors
    if (error && typeof error === "object" && "statusCode" in error) {
      throw error;
    }

    console.error("Error fetching NCRs:", error);
    throw createError({
      statusCode: 500,
      statusMessage: "Internal Server Error",
      data: {
        code: "INTERNAL_ERROR",
        message: "Failed to fetch NCRs",
      },
    });
  }
});
