<script setup lang="ts">
import { formatCurrency, formatDate } from "~/utils/format";

// SEO
useSeoMeta({
  title: "NCRs - Stock Management System",
  description: "View and manage Non-Conformance Reports",
});

// Composables
const router = useRouter();
const { canCreateNCR } = usePermissions();
const toast = useAppToast();

// Types
interface Location {
  id: string;
  code: string;
  name: string;
  type: string;
}

interface NCR {
  id: string;
  ncr_no: string;
  type: "MANUAL" | "PRICE_VARIANCE";
  status: "OPEN" | "SENT" | "CREDITED" | "REJECTED" | "RESOLVED";
  date: string;
  reason: string;
  quantity: number | null;
  value: number;
  auto_generated: boolean;
  location: Location;
  delivery_line: {
    id: string;
    item: {
      name: string;
      code: string;
    };
    unit_price: number;
    period_price: number;
  } | null;
  created_at: string;
}

// State
const loading = ref(false);
const error = ref<string | null>(null);
const ncrs = ref<NCR[]>([]);
const locations = ref<Location[]>([]);

// Filters
const filters = reactive({
  locationId: "all",
  type: null as "MANUAL" | "PRICE_VARIANCE" | null,
  status: "all" as "all" | "OPEN" | "SENT" | "CREDITED" | "REJECTED" | "RESOLVED",
  autoGenerated: null as boolean | null,
  startDate: "",
  endDate: "",
});

// Computed
const hasNCRs = computed(() => ncrs.value.length > 0);

// Location options for dropdown
const locationOptions = computed(() => [
  { label: "All Locations", value: "all" },
  ...locations.value.map((loc) => ({
    label: `${loc.name} (${loc.code})`,
    value: loc.id,
  })),
]);

// Type dropdown items
const typeDropdownItems = computed(() => [
  [
    {
      label: "All Types",
      icon: "i-lucide-list",
      active: filters.type === null,
      onSelect: () => selectType(null),
    },
    {
      label: "Manual",
      icon: "i-lucide-file-edit",
      active: filters.type === "MANUAL",
      onSelect: () => selectType("MANUAL"),
    },
    {
      label: "Price Variance",
      icon: "i-lucide-alert-triangle",
      active: filters.type === "PRICE_VARIANCE",
      onSelect: () => selectType("PRICE_VARIANCE"),
    },
  ],
]);

const currentTypeLabel = computed(() => {
  if (filters.type === "MANUAL") return "Manual";
  if (filters.type === "PRICE_VARIANCE") return "Price Variance";
  return "All Types";
});

const currentTypeIcon = computed(() => {
  if (filters.type === "MANUAL") return "i-lucide-file-edit";
  if (filters.type === "PRICE_VARIANCE") return "i-lucide-alert-triangle";
  return "i-lucide-list";
});

// Status dropdown items
const statusDropdownItems = computed(() => [
  [
    {
      label: "All Status",
      icon: "i-lucide-list",
      active: filters.status === "all",
      onSelect: () => selectStatus("all"),
    },
    {
      label: "Open",
      icon: "i-lucide-circle-dot",
      active: filters.status === "OPEN",
      onSelect: () => selectStatus("OPEN"),
    },
    {
      label: "Sent",
      icon: "i-lucide-send",
      active: filters.status === "SENT",
      onSelect: () => selectStatus("SENT"),
    },
    {
      label: "Credited",
      icon: "i-lucide-check-circle",
      active: filters.status === "CREDITED",
      onSelect: () => selectStatus("CREDITED"),
    },
    {
      label: "Rejected",
      icon: "i-lucide-x-circle",
      active: filters.status === "REJECTED",
      onSelect: () => selectStatus("REJECTED"),
    },
    {
      label: "Resolved",
      icon: "i-lucide-check-square",
      active: filters.status === "RESOLVED",
      onSelect: () => selectStatus("RESOLVED"),
    },
  ],
]);

const currentStatusLabel = computed(() => {
  if (filters.status === "all") return "All Status";
  return filters.status.charAt(0) + filters.status.slice(1).toLowerCase();
});

const currentStatusIcon = computed(() => {
  const icons = {
    all: "i-lucide-list",
    OPEN: "i-lucide-circle-dot",
    SENT: "i-lucide-send",
    CREDITED: "i-lucide-check-circle",
    REJECTED: "i-lucide-x-circle",
    RESOLVED: "i-lucide-check-square",
  };
  return icons[filters.status] || "i-lucide-list";
});

// Active filters
const activeFilters = computed(() => {
  const activeFiltersList: Array<{ key: string; label: string; value: string }> = [];

  if (filters.locationId && filters.locationId !== "all") {
    const location = locations.value.find((l) => l.id === filters.locationId);
    if (location) {
      activeFiltersList.push({
        key: "locationId",
        label: "Location",
        value: location.name,
      });
    }
  }

  if (filters.type) {
    activeFiltersList.push({
      key: "type",
      label: "Type",
      value: filters.type === "MANUAL" ? "Manual" : "Price Variance",
    });
  }

  if (filters.status !== "all") {
    activeFiltersList.push({
      key: "status",
      label: "Status",
      value: currentStatusLabel.value,
    });
  }

  if (filters.autoGenerated !== null) {
    activeFiltersList.push({
      key: "autoGenerated",
      label: "Auto-Generated",
      value: filters.autoGenerated ? "Yes" : "No",
    });
  }

  // Only show date range filter when BOTH dates are specified
  if (filters.startDate && filters.endDate) {
    activeFiltersList.push({
      key: "dateRange",
      label: "Date Range",
      value: `${formatDate(filters.startDate)} - ${formatDate(filters.endDate)}`,
    });
  }

  return activeFiltersList;
});

// Status badge helper
function getStatusColor(
  status: NCR["status"]
): "success" | "warning" | "error" | "neutral" | "primary" {
  const statusColors = {
    OPEN: "primary" as const,
    SENT: "warning" as const,
    CREDITED: "success" as const,
    REJECTED: "error" as const,
    RESOLVED: "neutral" as const,
  };
  return statusColors[status] || "neutral";
}

function getStatusLabel(status: NCR["status"]) {
  const statusLabels = {
    OPEN: "Open",
    SENT: "Sent",
    CREDITED: "Credited",
    REJECTED: "Rejected",
    RESOLVED: "Resolved",
  };
  return statusLabels[status] || status;
}

function getTypeLabel(type: NCR["type"]) {
  return type === "MANUAL" ? "Manual" : "Price Variance";
}

function getTypeBadgeColor(type: NCR["type"]): "primary" | "warning" {
  return type === "MANUAL" ? "primary" : "warning";
}

// Select handlers
function selectType(value: "MANUAL" | "PRICE_VARIANCE" | null) {
  filters.type = value;
  applyFilters();
}

function selectStatus(value: "all" | "OPEN" | "SENT" | "CREDITED" | "REJECTED" | "RESOLVED") {
  filters.status = value;
  applyFilters();
}

// Fetch NCRs
async function fetchNCRs() {
  loading.value = true;
  error.value = null;

  try {
    const params = new URLSearchParams();

    if (filters.locationId && filters.locationId !== "all") {
      params.append("locationId", filters.locationId);
    }
    if (filters.type) params.append("type", filters.type);
    if (filters.status !== "all") params.append("status", filters.status);
    if (filters.autoGenerated !== null) {
      params.append("autoGenerated", filters.autoGenerated.toString());
    }

    // Only apply date filter when BOTH dates are specified
    if (filters.startDate && filters.endDate) {
      params.append("startDate", filters.startDate);
      params.append("endDate", filters.endDate);
    }

    const response = await $fetch<{
      ncrs: NCR[];
      count: number;
    }>(`/api/ncrs?${params}`);

    ncrs.value = response.ncrs;
  } catch (err: unknown) {
    const fetchError = err as { data?: { message?: string } };
    error.value = fetchError?.data?.message || "Failed to fetch NCRs";
    console.error("Error fetching NCRs:", err);
    toast.error("Error", { description: error.value || undefined });
  } finally {
    loading.value = false;
  }
}

// Fetch locations
async function fetchLocations() {
  try {
    const response = await $fetch<{ locations: Location[] }>("/api/locations");
    locations.value = response.locations;
  } catch (err: unknown) {
    console.error("Error fetching locations:", err);
  }
}

// Filter handlers
function clearFilter(key: string) {
  if (key === "type") {
    filters.type = null;
  } else if (key === "status") {
    filters.status = "all";
  } else if (key === "locationId") {
    filters.locationId = "all";
  } else if (key === "autoGenerated") {
    filters.autoGenerated = null;
  } else if (key === "dateRange") {
    filters.startDate = "";
    filters.endDate = "";
  }
  fetchNCRs();
}

function applyFilters() {
  fetchNCRs();
}

// Row click handler
function handleRowClick(ncr: NCR) {
  router.push(`/ncrs/${ncr.id}`);
}

// Row keyboard handler for accessibility
function handleRowKeydown(event: KeyboardEvent, ncr: NCR) {
  if (event.key === "Enter" || event.key === " ") {
    event.preventDefault();
    handleRowClick(ncr);
  }
}

// Navigation
function goToNewNCR() {
  router.push("/ncrs/create");
}

// Watch location filter changes - apply immediately
watch(
  () => filters.locationId,
  () => {
    applyFilters();
  }
);

// Watch date range changes - only apply when BOTH dates are specified
watch(
  () => [filters.startDate, filters.endDate],
  ([newStartDate, newEndDate], [oldStartDate, oldEndDate]) => {
    // Only trigger fetch when:
    // 1. Both dates are now specified (complete range)
    // 2. OR a date was cleared (to remove the filter)
    const bothDatesSet = newStartDate !== "" && newEndDate !== "";
    const dateWasCleared =
      (oldStartDate !== "" && newStartDate === "") || (oldEndDate !== "" && newEndDate === "");

    if (bothDatesSet || dateWasCleared) {
      applyFilters();
    }
  }
);

// Initial load
onMounted(async () => {
  await fetchLocations();
  await fetchNCRs();
});
</script>

<template>
  <div class="px-0 py-0 md:px-4 md:py-1 space-y-3">
    <!-- Page Header -->
    <div class="flex items-center justify-between gap-3">
      <div class="flex items-center gap-2 sm:gap-4">
        <UIcon name="i-lucide-alert-circle" class="w-6 h-6 sm:w-10 sm:h-10 text-primary" />
        <div>
          <h1 class="text-xl sm:text-3xl font-bold text-primary">Non-Conformance Reports</h1>
          <p class="hidden sm:block text-sm text-[var(--ui-text-muted)] mt-1">
            Track and manage price variances and quality issues
          </p>
        </div>
      </div>
      <UButton
        v-if="canCreateNCR()"
        color="primary"
        icon="i-lucide-plus"
        size="lg"
        class="cursor-pointer rounded-full px-3 sm:px-6"
        @click="goToNewNCR"
      >
        <span class="hidden sm:inline">New NCR</span>
        <span class="sm:hidden">New</span>
      </UButton>
    </div>

    <!-- Filter Section -->
    <UCard class="card-elevated" :ui="{ body: 'p-3 sm:p-4' }">
      <!-- Desktop: Single row layout (lg and above) -->
      <div class="hidden lg:flex items-center gap-3">
        <!-- Location Dropdown -->
        <div class="flex-1 min-w-0 max-w-xs">
          <USelectMenu
            v-model="filters.locationId"
            :items="locationOptions"
            value-key="value"
            placeholder="All Locations"
            size="lg"
            class="w-full"
          >
            <template #leading>
              <UIcon name="i-lucide-map-pin" class="w-5 h-5" />
            </template>
          </USelectMenu>
        </div>

        <!-- Date Range Start -->
        <div class="flex-1 min-w-0 max-w-xs">
          <label class="sr-only" for="filter-start-date">Start date</label>
          <UInput
            id="filter-start-date"
            v-model="filters.startDate"
            type="date"
            icon="i-lucide-calendar"
            size="lg"
            class="w-full"
            placeholder="Start date"
          />
        </div>

        <!-- Date Range End -->
        <div class="flex-1 min-w-0 max-w-xs">
          <label class="sr-only" for="filter-end-date">End date</label>
          <UInput
            id="filter-end-date"
            v-model="filters.endDate"
            type="date"
            icon="i-lucide-calendar"
            size="lg"
            class="w-full"
            placeholder="End date"
          />
        </div>

        <!-- Type Dropdown (Far Right) -->
        <UDropdownMenu :items="typeDropdownItems" class="ml-auto">
          <UButton
            color="neutral"
            variant="outline"
            size="lg"
            class="cursor-pointer rounded-full px-5"
            trailing-icon="i-lucide-chevron-down"
          >
            <UIcon :name="currentTypeIcon" class="w-4 h-4 mr-2" />
            {{ currentTypeLabel }}
          </UButton>
        </UDropdownMenu>

        <!-- Status Dropdown -->
        <UDropdownMenu :items="statusDropdownItems">
          <UButton
            color="neutral"
            variant="outline"
            size="lg"
            class="cursor-pointer rounded-full px-5"
            trailing-icon="i-lucide-chevron-down"
          >
            <UIcon :name="currentStatusIcon" class="w-4 h-4 mr-2" />
            {{ currentStatusLabel }}
          </UButton>
        </UDropdownMenu>
      </div>

      <!-- Mobile: Stacked layout (below lg) -->
      <div class="flex flex-col gap-3 lg:hidden">
        <!-- Row 1: Location and Date Range -->
        <div class="flex items-center gap-3">
          <div class="flex-1 min-w-0">
            <USelectMenu
              v-model="filters.locationId"
              :items="locationOptions"
              value-key="value"
              placeholder="Location"
              size="lg"
              class="w-full"
            >
              <template #leading>
                <UIcon name="i-lucide-map-pin" class="w-5 h-5" />
              </template>
            </USelectMenu>
          </div>
        </div>

        <!-- Row 2: Date Inputs -->
        <div class="flex items-center gap-3">
          <div class="flex-1 min-w-0">
            <label class="sr-only" for="filter-start-date-mobile">Start date</label>
            <UInput
              id="filter-start-date-mobile"
              v-model="filters.startDate"
              type="date"
              icon="i-lucide-calendar"
              size="lg"
              class="w-full"
              placeholder="Start"
            />
          </div>
          <div class="flex-1 min-w-0">
            <label class="sr-only" for="filter-end-date-mobile">End date</label>
            <UInput
              id="filter-end-date-mobile"
              v-model="filters.endDate"
              type="date"
              icon="i-lucide-calendar"
              size="lg"
              class="w-full"
              placeholder="End"
            />
          </div>
        </div>

        <!-- Row 3: Type and Status Dropdowns (Icon-only) -->
        <div class="flex items-center gap-3">
          <UDropdownMenu :items="typeDropdownItems" class="flex-1">
            <UButton
              color="neutral"
              variant="outline"
              size="lg"
              class="cursor-pointer rounded-full w-full"
              trailing-icon="i-lucide-chevron-down"
              :title="`Type: ${currentTypeLabel}`"
            >
              <UIcon :name="currentTypeIcon" class="w-4 h-4 mr-2" />
              <span class="truncate">{{ currentTypeLabel }}</span>
            </UButton>
          </UDropdownMenu>

          <UDropdownMenu :items="statusDropdownItems" class="flex-1">
            <UButton
              color="neutral"
              variant="outline"
              size="lg"
              class="cursor-pointer rounded-full w-full"
              trailing-icon="i-lucide-chevron-down"
              :title="`Status: ${currentStatusLabel}`"
            >
              <UIcon :name="currentStatusIcon" class="w-4 h-4 mr-2" />
              <span class="truncate">{{ currentStatusLabel }}</span>
            </UButton>
          </UDropdownMenu>
        </div>
      </div>

      <!-- Active Filters -->
      <div v-if="activeFilters.length > 0" class="mt-4 pt-4 border-t border-[var(--ui-border)]">
        <div class="flex flex-wrap items-center gap-2">
          <span class="text-sm text-[var(--ui-text-muted)]">Active filters:</span>
          <UBadge
            v-for="filter in activeFilters"
            :key="filter.key"
            color="primary"
            variant="soft"
            class="cursor-pointer"
            @click="clearFilter(filter.key)"
          >
            {{ filter.label }}: {{ filter.value }}
            <UIcon name="i-lucide-x" class="ml-1 h-3 w-3" />
          </UBadge>
        </div>
      </div>
    </UCard>

    <!-- Error State -->
    <ErrorAlert v-if="error" :message="error" @retry="fetchNCRs" />

    <!-- Loading State -->
    <div v-if="loading" class="flex justify-center items-center py-12">
      <LoadingSpinner size="lg" color="primary" text="Loading NCRs..." />
    </div>

    <!-- Empty State -->
    <EmptyState
      v-else-if="!hasNCRs"
      icon="i-lucide-alert-circle"
      :title="activeFilters.length > 0 ? 'No NCRs found' : 'No NCRs yet'"
      :description="
        activeFilters.length > 0
          ? 'No NCRs match your current filters. Try adjusting your search criteria.'
          : 'NCRs are automatically created for price variances or can be created manually.'
      "
    >
      <template v-if="canCreateNCR() && activeFilters.length === 0" #actions>
        <UButton color="primary" icon="i-lucide-plus" class="cursor-pointer" @click="goToNewNCR">
          Create First NCR
        </UButton>
      </template>
    </EmptyState>

    <!-- NCRs Table -->
    <UCard v-else class="card-elevated" :ui="{ body: 'p-0' }">
      <div class="overflow-x-auto">
        <table class="min-w-full divide-y divide-[var(--ui-border)]">
          <thead>
            <tr class="bg-[var(--ui-bg-elevated)]">
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">NCR No</th>
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">Type</th>
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">Date</th>
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">Location</th>
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">Reason</th>
              <th class="px-4 py-3 text-right text-label uppercase tracking-wider">Value</th>
              <th class="px-4 py-3 text-left text-label uppercase tracking-wider">Status</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-[var(--ui-border)]">
            <tr
              v-for="ncr in ncrs"
              :key="ncr.id"
              tabindex="0"
              role="button"
              :aria-label="`View NCR ${ncr.ncr_no}`"
              class="hover:bg-[var(--ui-bg-elevated)] transition-colors cursor-pointer focus:outline-none focus:ring-2 focus:ring-primary focus:ring-inset"
              @click="handleRowClick(ncr)"
              @keydown="handleRowKeydown($event, ncr)"
            >
              <!-- NCR No -->
              <td class="px-4 py-4 text-[var(--ui-text)] font-medium">
                {{ ncr.ncr_no }}
                <UBadge
                  v-if="ncr.auto_generated"
                  color="neutral"
                  variant="soft"
                  size="xs"
                  class="ml-2"
                >
                  Auto
                </UBadge>
              </td>

              <!-- Type -->
              <td class="px-4 py-4">
                <UBadge :color="getTypeBadgeColor(ncr.type)" variant="subtle" size="md">
                  {{ getTypeLabel(ncr.type) }}
                </UBadge>
              </td>

              <!-- Date -->
              <td class="px-4 py-4 text-caption">
                {{ formatDate(ncr.date) }}
              </td>

              <!-- Location -->
              <td class="px-4 py-4">
                <div class="font-medium text-[var(--ui-text)]">{{ ncr.location.name }}</div>
                <div class="text-caption">
                  {{ ncr.location.code }}
                </div>
              </td>

              <!-- Reason -->
              <td class="px-4 py-4 max-w-xs truncate text-caption" :title="ncr.reason">
                {{ ncr.reason }}
              </td>

              <!-- Value -->
              <td class="px-4 py-4 text-right text-[var(--ui-text)] font-medium">
                {{ formatCurrency(ncr.value) }}
              </td>

              <!-- Status -->
              <td class="px-4 py-4">
                <UBadge :color="getStatusColor(ncr.status)" variant="subtle" size="md">
                  {{ getStatusLabel(ncr.status) }}
                </UBadge>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </UCard>
  </div>
</template>
