<script setup lang="ts">
import { formatCurrency, formatDate } from "~/utils/format";

// SEO
useSeoMeta({
  title: "NCRs - Stock Management System",
  description: "View and manage Non-Conformance Reports",
});

// Composables
const router = useRouter();
const { canCreateNCR } = usePermissions();
const toast = useAppToast();

// Types
interface Location {
  id: string;
  code: string;
  name: string;
  type: string;
}

interface NCR {
  id: string;
  ncr_no: string;
  type: "MANUAL" | "PRICE_VARIANCE";
  status: "OPEN" | "SENT" | "CREDITED" | "REJECTED" | "RESOLVED";
  date: string;
  reason: string;
  quantity: number | null;
  value: number;
  auto_generated: boolean;
  location: Location;
  delivery_line: {
    id: string;
    item: {
      name: string;
      code: string;
    };
    unit_price: number;
    period_price: number;
  } | null;
  created_at: string;
}

// State
const loading = ref(false);
const error = ref<string | null>(null);
const ncrs = ref<NCR[]>([]);
const locations = ref<Location[]>([]);

// Filters
const filters = reactive({
  locationId: "",
  type: "",
  status: "",
  autoGenerated: "",
  startDate: "",
  endDate: "",
});

// Computed
const hasNCRs = computed(() => ncrs.value.length > 0);

// Active filters
const activeFilters = computed(() => {
  const activeFiltersList: Array<{ key: string; label: string; value: any }> = [];
  if (filters.locationId) {
    const location = locations.value.find((l) => l.id === filters.locationId);
    if (location) {
      activeFiltersList.push({
        key: "locationId",
        label: "Location",
        value: location.name,
      });
    }
  }
  if (filters.type) {
    activeFiltersList.push({
      key: "type",
      label: "Type",
      value: filters.type === "MANUAL" ? "Manual" : "Price Variance",
    });
  }
  if (filters.status) {
    activeFiltersList.push({
      key: "status",
      label: "Status",
      value: filters.status.charAt(0) + filters.status.slice(1).toLowerCase(),
    });
  }
  if (filters.autoGenerated) {
    activeFiltersList.push({
      key: "autoGenerated",
      label: "Auto-Generated",
      value: filters.autoGenerated === "true" ? "Yes" : "No",
    });
  }
  if (filters.startDate) {
    activeFiltersList.push({
      key: "startDate",
      label: "Start Date",
      value: formatDate(filters.startDate),
    });
  }
  if (filters.endDate) {
    activeFiltersList.push({
      key: "endDate",
      label: "End Date",
      value: formatDate(filters.endDate),
    });
  }
  return activeFiltersList;
});

// Table columns
const columns = [
  { key: "ncr_no", label: "NCR No" },
  { key: "type", label: "Type" },
  { key: "date", label: "Date" },
  { key: "location", label: "Location" },
  { key: "reason", label: "Reason" },
  { key: "value", label: "Value" },
  { key: "status", label: "Status" },
];

// Status badge helper
function getStatusColor(
  status: NCR["status"],
): "success" | "warning" | "error" | "neutral" | "primary" {
  const statusColors = {
    OPEN: "primary" as const,
    SENT: "warning" as const,
    CREDITED: "success" as const,
    REJECTED: "error" as const,
    RESOLVED: "neutral" as const,
  };
  return statusColors[status] || "neutral";
}

function getStatusLabel(status: NCR["status"]) {
  const statusLabels = {
    OPEN: "Open",
    SENT: "Sent",
    CREDITED: "Credited",
    REJECTED: "Rejected",
    RESOLVED: "Resolved",
  };
  return statusLabels[status] || status;
}

function getTypeLabel(type: NCR["type"]) {
  return type === "MANUAL" ? "Manual" : "Price Variance";
}

function getTypeBadgeColor(type: NCR["type"]): "primary" | "warning" {
  return type === "MANUAL" ? "primary" : "warning";
}

// Fetch NCRs
async function fetchNCRs() {
  loading.value = true;
  error.value = null;

  try {
    const params = new URLSearchParams();

    if (filters.locationId) params.append("locationId", filters.locationId);
    if (filters.type) params.append("type", filters.type);
    if (filters.status) params.append("status", filters.status);
    if (filters.autoGenerated) params.append("autoGenerated", filters.autoGenerated);
    if (filters.startDate) params.append("startDate", filters.startDate);
    if (filters.endDate) params.append("endDate", filters.endDate);

    const response = await $fetch<{
      ncrs: NCR[];
      count: number;
    }>(`/api/ncrs?${params}`);

    ncrs.value = response.ncrs;
  } catch (err: any) {
    error.value = err?.data?.message || "Failed to fetch NCRs";
    console.error("Error fetching NCRs:", err);
  } finally {
    loading.value = false;
  }
}

// Fetch locations
async function fetchLocations() {
  try {
    const response = await $fetch<{ locations: Location[] }>("/api/locations");
    locations.value = response.locations;
  } catch (err: any) {
    console.error("Error fetching locations:", err);
  }
}

// Filter handlers
function clearFilter(key: string) {
  (filters as any)[key] = "";
  fetchNCRs();
}

function applyFilters() {
  fetchNCRs();
}

function clearAllFilters() {
  filters.locationId = "";
  filters.type = "";
  filters.status = "";
  filters.autoGenerated = "";
  filters.startDate = "";
  filters.endDate = "";
  applyFilters();
}

// Row click handler
function handleRowClick(ncr: NCR) {
  router.push(`/ncrs/${ncr.id}`);
}

// Navigation
function goToNewNCR() {
  router.push("/ncrs/create");
}

// Initial load
onMounted(async () => {
  await fetchLocations();
  await fetchNCRs();
});
</script>

<template>
  <div class="p-4 md:p-6">
    <div class="space-y-6">
      <!-- Page Header -->
      <LayoutPageHeader
        title="Non-Conformance Reports (NCR)"
        icon="i-lucide-alert-circle"
        :show-location="false"
        :show-period="true"
        location-scope="none"
      >
        <template #actions>
          <UButton
            v-if="canCreateNCR()"
            color="primary"
            icon="i-lucide-plus"
            label="New NCR"
            @click="goToNewNCR"
          />
        </template>
      </LayoutPageHeader>

      <!-- Filters -->
      <div class="card-elevated p-4">
        <h2 class="mb-4 text-label font-semibold">Filters</h2>

        <div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
          <!-- Location Filter -->
          <div>
            <label class="form-label">Location</label>
            <select v-model="filters.locationId" class="form-input w-full">
              <option value="">All Locations</option>
              <option v-for="location in locations" :key="location.id" :value="location.id">
                {{ location.name }} ({{ location.code }})
              </option>
            </select>
          </div>

          <!-- Type Filter -->
          <div>
            <label class="form-label">Type</label>
            <select v-model="filters.type" class="form-input w-full">
              <option value="">All Types</option>
              <option value="MANUAL">Manual</option>
              <option value="PRICE_VARIANCE">Price Variance</option>
            </select>
          </div>

          <!-- Status Filter -->
          <div>
            <label class="form-label">Status</label>
            <select v-model="filters.status" class="form-input w-full">
              <option value="">All Status</option>
              <option value="OPEN">Open</option>
              <option value="SENT">Sent</option>
              <option value="CREDITED">Credited</option>
              <option value="REJECTED">Rejected</option>
              <option value="RESOLVED">Resolved</option>
            </select>
          </div>

          <!-- Auto-Generated Filter -->
          <div>
            <label class="form-label">Auto-Generated</label>
            <select v-model="filters.autoGenerated" class="form-input w-full">
              <option value="">All</option>
              <option value="true">Yes</option>
              <option value="false">No</option>
            </select>
          </div>
        </div>

        <!-- Date Range -->
        <div class="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
          <div>
            <label class="form-label">Start Date</label>
            <input
              v-model="filters.startDate"
              type="date"
              class="form-input w-full"
              placeholder="Start date"
            />
          </div>

          <div>
            <label class="form-label">End Date</label>
            <input
              v-model="filters.endDate"
              type="date"
              class="form-input w-full"
              placeholder="End date"
            />
          </div>
        </div>

        <!-- Filter Actions -->
        <div class="mt-4 flex gap-2">
          <UButton
            color="primary"
            icon="i-lucide-filter"
            label="Apply Filters"
            @click="applyFilters"
          />
          <UButton
            color="neutral"
            variant="outline"
            icon="i-lucide-x"
            label="Clear All"
            @click="clearAllFilters"
          />
        </div>

        <!-- Active Filters -->
        <div v-if="activeFilters.length > 0" class="mt-4 flex flex-wrap gap-2">
          <span class="text-caption">Active filters:</span>
          <UBadge
            v-for="filter in activeFilters"
            :key="filter.key"
            color="primary"
            variant="soft"
            class="cursor-pointer"
            @click="clearFilter(filter.key)"
          >
            {{ filter.label }}: {{ filter.value }}
            <UIcon name="i-lucide-x" class="ml-1 h-3 w-3" />
          </UBadge>
        </div>
      </div>

      <!-- Error State -->
      <ErrorAlert v-if="error" :message="error" @retry="fetchNCRs" class="mb-6" />

      <!-- Loading State -->
      <TableSkeleton v-if="loading" :columns="7" :rows="8" />

      <!-- NCRs Table -->
      <div
        v-else-if="hasNCRs"
        class="overflow-hidden rounded-lg border border-default bg-elevated"
      >
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead class="border-b border-default bg-zinc-50 dark:bg-zinc-900">
              <tr>
                <th
                  v-for="col in columns"
                  :key="col.key"
                  class="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-muted"
                >
                  {{ col.label }}
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-default">
              <tr
                v-for="ncr in ncrs"
                :key="ncr.id"
                class="cursor-pointer transition-colors hover:bg-zinc-50 dark:hover:bg-zinc-900"
                @click="handleRowClick(ncr)"
              >
                <td class="whitespace-nowrap px-4 py-3 text-body font-medium">
                  {{ ncr.ncr_no }}
                  <UBadge
                    v-if="ncr.auto_generated"
                    color="neutral"
                    variant="soft"
                    size="xs"
                    class="ml-2"
                  >
                    Auto
                  </UBadge>
                </td>
                <td class="px-4 py-3 text-body">
                  <UBadge :color="getTypeBadgeColor(ncr.type)" variant="soft">
                    {{ getTypeLabel(ncr.type) }}
                  </UBadge>
                </td>
                <td class="whitespace-nowrap px-4 py-3 text-body">
                  {{ formatDate(ncr.date) }}
                </td>
                <td class="px-4 py-3 text-body">
                  <div class="font-medium">{{ ncr.location.name }}</div>
                  <div class="text-caption">
                    {{ ncr.location.code }}
                  </div>
                </td>
                <td class="px-4 py-3 text-body max-w-xs truncate" :title="ncr.reason">
                  {{ ncr.reason }}
                </td>
                <td class="whitespace-nowrap px-4 py-3 text-body font-medium">
                  {{ formatCurrency(ncr.value) }}
                </td>
                <td class="px-4 py-3 text-body">
                  <UBadge :color="getStatusColor(ncr.status)" variant="soft">
                    {{ getStatusLabel(ncr.status) }}
                  </UBadge>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Empty State -->
      <EmptyState
        v-else
        icon="i-lucide-alert-circle"
        title="No NCRs Found"
        :description="
          activeFilters.length > 0
            ? 'No NCRs match your current filters. Try adjusting your search criteria.'
            : 'No NCRs have been recorded yet. NCRs are automatically created for price variances or can be created manually.'
        "
      >
        <template v-if="canCreateNCR()" #action>
          <UButton
            color="primary"
            icon="i-lucide-plus"
            label="New NCR"
            @click="goToNewNCR"
          />
        </template>
      </EmptyState>
    </div>
  </div>
</template>
